# 100 numpy exercises

This is a collection of exercises that have perform.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [142]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: D:/NUST/annaconda/New folder/Library/include
    lib directory: D:/NUST/annaconda/New folder/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [126]:
array = np.array([1,2,3,4,5])
print(array.dtype)

int32


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
vector = np.zeros(10)
vector[4] = 1 
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [13]:
vector = np.arange(10, 50)
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [127]:
matrix = np.arange(0,9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [28]:
my_list = [1, 2, 0, 0, 4, 0]
non_zero_indices = []
for i in range(len(my_list)):
    if my_list[i] != 0:
        non_zero_indices.append(i)
print(non_zero_indices)

[0, 1, 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [16]:
matrix_1 = np.ones((3,3))
matrix_1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [21]:
random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[0.66428058 0.51686214 0.29814204]
  [0.726231   0.02516578 0.84225415]
  [0.6751348  0.22834335 0.74874733]]

 [[0.96127157 0.69303398 0.08342696]
  [0.26435847 0.83026883 0.33538199]
  [0.02365872 0.870621   0.51631387]]

 [[0.811574   0.05071375 0.9550189 ]
  [0.81397944 0.1127177  0.92205318]
  [0.61462862 0.45510915 0.6885332 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [25]:
random_array = np.random.rand(10,10)
print(random_array)
print("the minimum value is",random_array.min())
print("the maximum value is",random_array.max())

[[0.92191343 0.78441576 0.36805031 0.20194144 0.63650731 0.46644954
  0.96819237 0.755782   0.3393531  0.9036809 ]
 [0.37179424 0.04857745 0.9823576  0.96120956 0.34873837 0.34417182
  0.41313622 0.95937401 0.30014166 0.97670356]
 [0.50152882 0.84685598 0.146841   0.71603927 0.46800002 0.40736031
  0.63214007 0.14163296 0.8354221  0.55979539]
 [0.71347175 0.22202898 0.12514507 0.64804967 0.48853557 0.15813281
  0.18065783 0.07652831 0.70466033 0.23913052]
 [0.49829852 0.39004804 0.84083607 0.03136785 0.0212846  0.6650496
  0.60785655 0.07282865 0.32211131 0.6234607 ]
 [0.37979512 0.37235981 0.75652539 0.96461308 0.93855322 0.28563342
  0.40719093 0.1883672  0.79111328 0.49847734]
 [0.79808198 0.75849886 0.52059436 0.761353   0.48591535 0.08689711
  0.0941025  0.43193706 0.1235129  0.56990808]
 [0.47732962 0.87083722 0.75437728 0.40959323 0.14806138 0.09705343
  0.61879872 0.66056505 0.29378051 0.14396137]
 [0.1432188  0.2486929  0.62435198 0.6946719  0.59782874 0.21434635
  0.40450564 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [29]:
random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)
print("Random Vector:", random_vector)
print("Mean Value:", mean_value)

Random Vector: [0.60224981 0.04690107 0.79324271 0.40181404 0.20885708 0.43856824
 0.98417607 0.42961693 0.73486963 0.7887009  0.30155138 0.20116997
 0.11001932 0.03553151 0.26130313 0.42745821 0.54189832 0.01139905
 0.37769655 0.92953528 0.95396386 0.59234272 0.49542612 0.10962411
 0.52824171 0.84465127 0.52363764 0.16078637 0.49220397 0.49953365]
Mean Value: 0.46089901980791986


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [137]:

original_array = np.array([[0,0],[0,0]])
padded_array = np.pad(original_array, pad_width=1,mode = "constant",constant_values=1)
padded_array

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [138]:
original_array = np.array([[1,2,3,4],[5,6,7,8],[2,3,4,5],[6,7,8,9]])
padded_array = np.pad(original_array, pad_width=1,mode = "constant",constant_values=1)
padded_array

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 2, 3, 4, 1],
       [1, 5, 6, 7, 8, 1],
       [1, 2, 3, 4, 5, 1],
       [1, 6, 7, 8, 9, 1],
       [1, 1, 1, 1, 1, 1]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [32]:
0 * np.nan


nan

In [35]:
np.nan == np.nan

False

In [36]:
np.inf > np.nan

False

In [37]:
np.nan - np.nan

nan

In [38]:
np.nan in set([np.nan])

True

In [39]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [140]:
array = np.array([[1,3,4,5,6],[9,2,6,8,5],[8,6,3,9,4],[6,7,3,4,6],[6,7,3,4,5]])
array

array([[1, 3, 4, 5, 6],
       [9, 2, 6, 8, 5],
       [8, 6, 3, 9, 4],
       [6, 7, 3, 4, 6],
       [6, 7, 3, 4, 5]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [46]:
checkerboard_2x2 = np.array([[1, 0],
                             [0, 1]])

checkerboard_8x8 = np.tile(checkerboard_2x2, (4, 4))

print(checkerboard_8x8)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [144]:
matrix = np.random.rand(5, 5)
min_val = matrix.min()
max_val = matrix.max()

normalized_matrix = (matrix - min_val) / (max_val - min_val)

print("Original Matrix:")
print(matrix)
print("Normalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.79987173 0.48016337 0.8903218  0.98914108 0.24409272]
 [0.92583345 0.47334462 0.25101006 0.19543012 0.63640949]
 [0.41947566 0.83252767 0.79679763 0.1769185  0.22172841]
 [0.09368809 0.71684122 0.15198829 0.66942047 0.43834323]
 [0.20199147 0.99074556 0.3881967  0.09511894 0.05101056]]
Normalized Matrix:
[[0.80211085 0.47549001 0.89451656 0.99547244 0.23431522]
 [0.93079602 0.46852383 0.24138213 0.18460048 0.63511436]
 [0.41349015 0.83547286 0.79897029 0.16568862 0.21146737]
 [0.08065866 0.71728512 0.14021938 0.66883908 0.43276567]
 [0.19130369 0.99711161 0.38153491 0.08212045 0.03705839]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [50]:

rgba_dtype = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])
color_array = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=rgba_dtype)
print(color_array)


[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [51]:
matrix_5x3 = np.random.rand(5, 3)
matrix_3x2 = np.random.rand(3, 2)
result = np.dot(matrix_5x3, matrix_3x2)
print("5x3 Matrix:")
print(matrix_5x3)
print("\n3x2 Matrix:")
print(matrix_3x2)
print("\nResult of multiplication (5x2 Matrix):")
print(result)


5x3 Matrix:
[[0.38107118 0.77261119 0.22037184]
 [0.49132682 0.68438072 0.40019627]
 [0.57041671 0.00730174 0.70371609]
 [0.70988905 0.25080934 0.67757441]
 [0.14676158 0.41133968 0.7335015 ]]

3x2 Matrix:
[[0.84981826 0.73078035]
 [0.84871876 0.56470846]
 [0.34230575 0.26617548]]

Result of multiplication (5x2 Matrix):
[[1.05500541 0.77343698]
 [1.13537474 0.85205   ]
 [0.73183373 0.60828465]
 [1.04808089 0.84076082]
 [0.72491416 0.53477759]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [52]:
print(sum(range(5),-1))

9


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [53]:
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [55]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

NameError: name 'Z' is not defined

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [145]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

# Find common values
common_values = np.intersect1d(array1, array2)

print(common_values)# Example arrays

[4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [147]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\ITL HUNZA\AppData\Local\Temp\ipykernel_11180\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [66]:
from datetime import datetime, timedelta
today = datetime.now().date()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print(f"Yesterday: {yesterday}")
print(f"Today: {today}")
print(f"Tomorrow: {tomorrow}")


Yesterday: 2024-08-16
Today: 2024-08-17
Tomorrow: 2024-08-18


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [68]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
A_plus_B = A + B
neg_A_div_2 = -A / 2
result = A_plus_B * neg_A_div_2

print(result)


[ -2.5  -7.  -13.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [150]:
row_values = np.arange(5)
matrix = np.repeat(row_values.reshape(1, -1), 5, axis=0)
print(matrix)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [74]:
def integer_generator(n):
    for i in range(n):
        yield i

gen = integer_generator(10)
array = np.array(list(gen))

print(array)


[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [155]:
vector = np.linspace(0, 1, 12)[1:-1]

print(vector)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [77]:
random_vector = np.random.rand(10)
sorted_vector = np.sort(random_vector)

print("Original Random Vector:")
print(random_vector)

print("\nSorted Vector:")
print(sorted_vector)


Original Random Vector:
[0.97509349 0.91303402 0.11146833 0.72676337 0.58678935 0.69998777
 0.75259308 0.73796164 0.60111896 0.89745053]

Sorted Vector:
[0.11146833 0.58678935 0.60111896 0.69998777 0.72676337 0.73796164
 0.75259308 0.89745053 0.91303402 0.97509349]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [78]:
array = np.array([1, 2, 3, 4, 5])
result = sum(array.tolist())

print("Sum using Python's built-in sum():", result)


Sum using Python's built-in sum(): 15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [79]:
are_close = np.allclose(A, B)
print("Are A and B approximately equal?")
print(are_close)


Are A and B approximately equal?
False


#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [88]:


positions = np.array([(1, 2), (3, 4), (5, 6)], dtype=[('x', float), ('y', float)])
colors = np.array([(255, 0, 0), (0, 255, 0), (0, 0, 255)], dtype=[('r', int), ('g', int), ('b', int)])

# Combine positions and colors into a structured array
dtype = [('position', positions.dtype), ('color', colors.dtype)]
structured_array = np.array(list(zip(positions, colors)), dtype=dtype)

print("Structured Array:")
print(structured_array)


Structured Array:
[((1., 2.), (255,   0,   0)) ((3., 4.), (  0, 255,   0))
 ((5., 6.), (  0,   0, 255))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [97]:

# Create a sample matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original Matrix:")
print(matrix)

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the mean from each row
normalized_matrix = matrix - row_means

print("\nMatrix after subtracting the mean of each row:")
print(normalized_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix after subtracting the mean of each row:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
import numpy as np

# Define the arrays
array1 = np.array([[1, 2, 3]])  # Shape (1, 3)
array2 = np.array([[4], [5], [6]])  # Shape (3, 1)

# Compute the sum using broadcasting
result = array1 + array2

# Display the result
print("Result:\n", result)


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [107]:

# Example matrices
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# Compute the dot product
dot_product = np.dot(A, B)

# Extract the diagonal of the dot product matrix
diagonal = np.diag(dot_product)

print("Dot Product:\n", dot_product)
print("Diagonal of Dot Product:", diagonal)


Dot Product:
 [[ 58  64]
 [139 154]]
Diagonal of Dot Product: [ 58 154]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [109]:
import numpy as np

# Create example arrays
A = np.random.rand(5, 5, 3)  # Shape (5, 5, 3)
B = np.random.rand(5, 5)     # Shape (5, 5)

# Multiply A by B
# Broadcasting B to shape (5, 5, 3) and then performing element-wise multiplication
result = A * B[:, :, np.newaxis]

print("Array A:\n", A)
print("Array B:\n", B)
print("Result:\n", result)


Array A:
 [[[0.47047296 0.57539662 0.60918016]
  [0.68270587 0.77773861 0.61175142]
  [0.3599636  0.58780889 0.97948059]
  [0.16535955 0.97051651 0.06543667]
  [0.84040164 0.81067368 0.72000277]]

 [[0.04801847 0.46642585 0.30144659]
  [0.11715511 0.76612    0.66452921]
  [0.27070028 0.1152277  0.16910037]
  [0.79476425 0.73318442 0.26387432]
  [0.99156437 0.81684905 0.87020853]]

 [[0.54161636 0.07994231 0.06940512]
  [0.86342833 0.85232522 0.93567333]
  [0.98172845 0.77680715 0.17718584]
  [0.6073273  0.72748251 0.57965559]
  [0.40843619 0.23599978 0.4295243 ]]

 [[0.01460825 0.19103259 0.17428548]
  [0.80209916 0.28315212 0.5478269 ]
  [0.28439268 0.87588584 0.25492143]
  [0.75665798 0.23556128 0.70057723]
  [0.18763202 0.5092843  0.96425199]]

 [[0.03981026 0.82898067 0.62102476]
  [0.05613991 0.59839182 0.06370206]
  [0.19585024 0.97829583 0.2805924 ]
  [0.15031008 0.46670792 0.12582383]
  [0.57307066 0.45962402 0.44779205]]]
Array B:
 [[0.69359983 0.19189831 0.64551008 0.22690537

#### 72. How to swap two rows of an array? (★★★)

In [156]:
import numpy as np

# Create an example 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Indices of rows to swap
i, j = 0, 2

# Swap rows i and j
array[[i, j]] = array[[j, i]]

print("Array after swapping rows:\n", array)


Array after swapping rows:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)